services:

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    build: ./.docker/nginx
    ports:
      - '${PROJECT_PORT}:80'
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  php:
    container_name: ${PROJECT_NAME}_php
    build: ./.docker/php
    volumes:
      - ./:/var/www/html

  mysql:
    container_name: ${PROJECT_NAME}_mysql
    build: ./.docker/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_ROOT_HOST=%"
    volumes:
      - ./:/app
      - db-data:/var/lib/mysql
    ports:
      - "33320:3306"

volumes:
  db-data:
